theme: jekyll-theme-cayman
title: My Own Space
SEOTitle: 我的个人博客 | htmc's own space   	 #显示在浏览器上搜索的时候显示的标题
#header-img: img/post-bg-rwd.jpg 显示在首页的背景图片
email: hexiaotong_alvin@163.com	
description: "technical articles and life methodology"  			 #网站介绍
keyword: "elvin, htmc, htmc Blog, htmc,hexiaotong, html, javascript, css, lifestyle" #关键词
url: "https://elvinhtmc.github.io"          # 这个就是填写你的博客地址
baseurl: ""      # 这个我们不用填写
